### ISSUE TITLE
Fresh install of plugin prevents compiling my site

### ISSUE THREAD

**Issue by niklas-fischer** [infracost/docusaurus-plugin-plausible#2]
After installing your plugin under Docusaurus 2 Alpha 64, the page cannot be created via 'yarn start'. The error is very cryptic (see attachment)
[2020-09-14T11_52_14_128Z-debug.log](https://github.com/infracost/docusaurus-plugin-plausible/files/5218293/2020-09-14T11_52_14_128Z-debug.log)

**Comment by aliscott** [comment]
Thanks @niklas-fischer. This looks like it might be an issue with your node_modules. You can try deleting your `package-lock.json` and `node_modules` dir and re-running `npm install` or `yarn install` to see if that fixes this.
